export type GeoConsent = 'unknown' | 'accepted' | 'denied';

export interface LocationVisit {
  id: string;
  lat: number;
  lng: number;
  accuracy: number | null;
  city: string;
  state: string;
  country: string;
  neighborhood: string;
  street: string;
  postcode: string;
  address: string;
  label: string;
  path: string;
  at: string;
  kmFromStore: number | null;
  device: string;
  os: string;
  browser: string;
  language: string;
  languages: string;
  timezone: string;
  screen: string;
  referrer: string;
  pageUrl: string;
  ip: string;
  isp: string;
  ipCity: string;
  ipRegion: string;
  ipCountry: string;
  userAgent: string;
  connection: string;
  platform: string;
  cores: string;
  memory: string;
  altitude: number | null;
  heading: number | null;
  speed: number | null;
}
